DROP TABLE IF EXISTS Cases cascade;
DROP TABLE IF EXISTS Checkinouts cascade;
DROP TABLE IF EXISTS Stores cascade;
DROP TABLE IF EXISTS Buildings cascade;
DROP TABLE IF EXISTS Locations cascade;
DROP TABLE IF EXISTS UserGroups cascade;
DROP TABLE IF EXISTS Groups cascade;
DROP TABLE IF EXISTS Users cascade;
DROP TABLE IF EXISTS Roles cascade;