# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tracking_pb2 as tracking__pb2


class TrackingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/SafeEntry.TrackingService/Login',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.User.FromString,
                )
        self.CreateCheckInIndividual = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckInIndividual',
                request_serializer=tracking__pb2.Location.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckInGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckInGroup',
                request_serializer=tracking__pb2.Location.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckOutIndividual = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckOutIndividual',
                request_serializer=tracking__pb2.CheckOut.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckOutGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckOutGroup',
                request_serializer=tracking__pb2.CheckOut.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.GetSafeEntry = channel.unary_stream(
                '/SafeEntry.TrackingService/GetSafeEntry',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.SafeEntry.FromString,
                )
        self.CreateReportCovidCase = channel.stream_unary(
                '/SafeEntry.TrackingService/CreateReportCovidCase',
                request_serializer=tracking__pb2.Location.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.GetAllNotificiationByUser = channel.unary_stream(
                '/SafeEntry.TrackingService/GetAllNotificiationByUser',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Notificiation.FromString,
                )
        self.GetAllLocations = channel.unary_stream(
                '/SafeEntry.TrackingService/GetAllLocations',
                request_serializer=tracking__pb2.Empty.SerializeToString,
                response_deserializer=tracking__pb2.Location.FromString,
                )
        self.GetCheckOutOptionsIndividual = channel.unary_stream(
                '/SafeEntry.TrackingService/GetCheckOutOptionsIndividual',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.CheckOut.FromString,
                )
        self.GetCheckOutOptionsGroup = channel.unary_stream(
                '/SafeEntry.TrackingService/GetCheckOutOptionsGroup',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.CheckOut.FromString,
                )
        self.GetAllUsers = channel.unary_stream(
                '/SafeEntry.TrackingService/GetAllUsers',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.User.FromString,
                )
        self.GetGroupsByUser = channel.unary_stream(
                '/SafeEntry.TrackingService/GetGroupsByUser',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Group.FromString,
                )
        self.CreateGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateGroup',
                request_serializer=tracking__pb2.Group.SerializeToString,
                response_deserializer=tracking__pb2.Group.FromString,
                )
        self.AddUserToGroup = channel.stream_unary(
                '/SafeEntry.TrackingService/AddUserToGroup',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.GetCovidLocationByUser = channel.unary_stream(
                '/SafeEntry.TrackingService/GetCovidLocationByUser',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Location.FromString,
                )
        self.LatencyTest = channel.unary_unary(
                '/SafeEntry.TrackingService/LatencyTest',
                request_serializer=tracking__pb2.Time.SerializeToString,
                response_deserializer=tracking__pb2.Empty.FromString,
                )


class TrackingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """MAIN PROCEDURE CALLS

        1. Login 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckInIndividual(self, request, context):
        """2. Perform Individual Check in 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckInGroup(self, request, context):
        """3. Perform Group Check in 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckOutIndividual(self, request, context):
        """4. Perform Individual Check Out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckOutGroup(self, request, context):
        """5. Perform Group Check Out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSafeEntry(self, request, context):
        """6. Listing Safe Entry History
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReportCovidCase(self, request_iterator, context):
        """7. Create Covid Case By Location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllNotificiationByUser(self, request, context):
        """8. Get Notificiation of User
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllLocations(self, request, context):
        """SUB PROCEDURE CALLS

        Get All Locations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckOutOptionsIndividual(self, request, context):
        """Get all possible check-out options
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckOutOptionsGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Get All Users registered in the system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupsByUser(self, request, context):
        """Get All Groups that user is in
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Create Group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToGroup(self, request_iterator, context):
        """Adding User to Group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCovidLocationByUser(self, request, context):
        """Get Locations that user has visited in the last 14days
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatencyTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.User.SerializeToString,
            ),
            'CreateCheckInIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckInIndividual,
                    request_deserializer=tracking__pb2.Location.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckInGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckInGroup,
                    request_deserializer=tracking__pb2.Location.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckOutIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckOutIndividual,
                    request_deserializer=tracking__pb2.CheckOut.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckOutGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckOutGroup,
                    request_deserializer=tracking__pb2.CheckOut.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'GetSafeEntry': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSafeEntry,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.SafeEntry.SerializeToString,
            ),
            'CreateReportCovidCase': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateReportCovidCase,
                    request_deserializer=tracking__pb2.Location.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'GetAllNotificiationByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllNotificiationByUser,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Notificiation.SerializeToString,
            ),
            'GetAllLocations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllLocations,
                    request_deserializer=tracking__pb2.Empty.FromString,
                    response_serializer=tracking__pb2.Location.SerializeToString,
            ),
            'GetCheckOutOptionsIndividual': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCheckOutOptionsIndividual,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.CheckOut.SerializeToString,
            ),
            'GetCheckOutOptionsGroup': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCheckOutOptionsGroup,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.CheckOut.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.User.SerializeToString,
            ),
            'GetGroupsByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetGroupsByUser,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Group.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=tracking__pb2.Group.FromString,
                    response_serializer=tracking__pb2.Group.SerializeToString,
            ),
            'AddUserToGroup': grpc.stream_unary_rpc_method_handler(
                    servicer.AddUserToGroup,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'GetCovidLocationByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCovidLocationByUser,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Location.SerializeToString,
            ),
            'LatencyTest': grpc.unary_unary_rpc_method_handler(
                    servicer.LatencyTest,
                    request_deserializer=tracking__pb2.Time.FromString,
                    response_serializer=tracking__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SafeEntry.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/Login',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckInIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckInIndividual',
            tracking__pb2.Location.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckInGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckInGroup',
            tracking__pb2.Location.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckOutIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckOutIndividual',
            tracking__pb2.CheckOut.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckOutGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckOutGroup',
            tracking__pb2.CheckOut.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSafeEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetSafeEntry',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.SafeEntry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReportCovidCase(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SafeEntry.TrackingService/CreateReportCovidCase',
            tracking__pb2.Location.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllNotificiationByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetAllNotificiationByUser',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Notificiation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetAllLocations',
            tracking__pb2.Empty.SerializeToString,
            tracking__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCheckOutOptionsIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetCheckOutOptionsIndividual',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.CheckOut.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCheckOutOptionsGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetCheckOutOptionsGroup',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.CheckOut.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetAllUsers',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetGroupsByUser',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Group.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateGroup',
            tracking__pb2.Group.SerializeToString,
            tracking__pb2.Group.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserToGroup(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SafeEntry.TrackingService/AddUserToGroup',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCovidLocationByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetCovidLocationByUser',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LatencyTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/LatencyTest',
            tracking__pb2.Time.SerializeToString,
            tracking__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
