# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tracking_pb2 as tracking__pb2


class TrackingServiceStub(object):
    """Procedure Needed
    1. Perform Individual Check-in
    2. Perform Individual Check-out
    3. Perform Group Check-in
    4. Perform Group Check-out
    5. Create Groups
    6. Add User to Groups
    7. Trigger Covid Cases 7.5 Send Notificiation to users
    8. List all SafeEntry locations
    9. Create report covid case

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/SafeEntry.TrackingService/Login',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckInIndividual = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckInIndividual',
                request_serializer=tracking__pb2.CheckInIndividual.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckOutIndividual = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckOutIndividual',
                request_serializer=tracking__pb2.CheckInIndividual.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckInGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckInGroup',
                request_serializer=tracking__pb2.CheckInGroup.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateCheckOutGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateCheckOutGroup',
                request_serializer=tracking__pb2.CheckInGroup.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.CreateGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateGroup',
                request_serializer=tracking__pb2.Group.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.AddUserToGroup = channel.unary_unary(
                '/SafeEntry.TrackingService/AddUserToGroup',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )
        self.GetSafeEntry = channel.unary_stream(
                '/SafeEntry.TrackingService/GetSafeEntry',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.SafeEntry.FromString,
                )
        self.CreateReportCovidCase = channel.unary_unary(
                '/SafeEntry.TrackingService/CreateReportCovidCase',
                request_serializer=tracking__pb2.User.SerializeToString,
                response_deserializer=tracking__pb2.Status.FromString,
                )


class TrackingServiceServicer(object):
    """Procedure Needed
    1. Perform Individual Check-in
    2. Perform Individual Check-out
    3. Perform Group Check-in
    4. Perform Group Check-out
    5. Create Groups
    6. Add User to Groups
    7. Trigger Covid Cases 7.5 Send Notificiation to users
    8. List all SafeEntry locations
    9. Create report covid case

    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckInIndividual(self, request, context):
        """1
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckOutIndividual(self, request, context):
        """2; Need duplicate Here? 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckInGroup(self, request, context):
        """3; Need to come back here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckOutGroup(self, request, context):
        """4. Need duplicate Here? 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """5.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToGroup(self, request, context):
        """6. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSafeEntry(self, request, context):
        """7. (Come back here)

        8
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReportCovidCase(self, request, context):
        """9. Self report covid case
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckInIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckInIndividual,
                    request_deserializer=tracking__pb2.CheckInIndividual.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckOutIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckOutIndividual,
                    request_deserializer=tracking__pb2.CheckInIndividual.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckInGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckInGroup,
                    request_deserializer=tracking__pb2.CheckInGroup.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateCheckOutGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckOutGroup,
                    request_deserializer=tracking__pb2.CheckInGroup.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=tracking__pb2.Group.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'AddUserToGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToGroup,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
            'GetSafeEntry': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSafeEntry,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.SafeEntry.SerializeToString,
            ),
            'CreateReportCovidCase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReportCovidCase,
                    request_deserializer=tracking__pb2.User.FromString,
                    response_serializer=tracking__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SafeEntry.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Procedure Needed
    1. Perform Individual Check-in
    2. Perform Individual Check-out
    3. Perform Group Check-in
    4. Perform Group Check-out
    5. Create Groups
    6. Add User to Groups
    7. Trigger Covid Cases 7.5 Send Notificiation to users
    8. List all SafeEntry locations
    9. Create report covid case

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/Login',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckInIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckInIndividual',
            tracking__pb2.CheckInIndividual.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckOutIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckOutIndividual',
            tracking__pb2.CheckInIndividual.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckInGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckInGroup',
            tracking__pb2.CheckInGroup.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCheckOutGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateCheckOutGroup',
            tracking__pb2.CheckInGroup.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateGroup',
            tracking__pb2.Group.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserToGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/AddUserToGroup',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSafeEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SafeEntry.TrackingService/GetSafeEntry',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.SafeEntry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReportCovidCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeEntry.TrackingService/CreateReportCovidCase',
            tracking__pb2.User.SerializeToString,
            tracking__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
